site_name: Coluna documentation
repo_url: https://github.com/atoptima/Coluna.jl
site_description: Branch-and-cut-and-price Optimizer for JuMP/MOI
site_author: atoptima

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
  - Installation: installation.md
  - Introduction: introduction.md
  - Basic Example: basic.md
